### PR TITLE
Josh fix doc typo

### PR DESCRIPTION
**Pull request by jnewman**
Might be confusing for a user who scans the docs and tries setting the directive to `On` when the module expects `on`.

### CODE REVIEW

**Comment by reversefold** [comment]
:+1:

**Comment by jib** [comment]
In production, we definitely use On, not 'on' - what makes you say this is what the module expects? (i'm pretty sure it's case insensitive actually) Maybe there's another bug somewhere?

```
jib@beacon-a101:/etc/apache2$ grep -nri QS2Cookie .
./sites-enabled/entrypoints/event.gif.entrypoint:122:           QS2Cookie On
```

**Comment by jnewman** [comment]
K, I'll update the other way. There's both `On` and `on` in the documentation.

**Comment by jnewman** [comment]
Should it be `On|Off` in the docs?

**Comment by jnewman** [comment]
This just makes the DOCUMENTATION file consistent on using On v. on. I think you're right about it being case insensitive, just figured we should stick to one.

**Comment by jib** [comment]
good catch, thanks.

**Pull request merged**
